### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by amelie314**
My website is at
http://3.131.18.21:3000/
Thank you!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
http://3.131.18.21:3000/api/attractions?page=0 should only include first 12 attraction data, and http://3.131.18.21:3000/api/attractions?page=1 includes next 12 attraction data. http://3.131.18.21:3000/api/attractions?page=0&keyword=%E5%8C%97 should only include first 12 attraction data which meet the keyword, and so on.

Fix this issue and re-request review.

**Comment by amelie314** [comment]
fixed the 2 issues!

**Comment by cwpeng** [comment]
Re-request review from top right corner of this pull request so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
