### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by amelie314**
完成第六週作業 0ade799999bb542fad927d838f036784254c0de9

- 陳慧樺
- http://3.131.18.21:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Don't show get prime dialog for end users.
2. Clear booking data after successful checking out.

**Comment by amelie314** [comment]
fixed the problems. thanks!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by amelie314** [comment]
- 改用 Connection pool

**Review by cwpeng — APPROVED** [review]
Good improvement.

**Pull request merged**
