### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by amelie314**
finished Guide_Part3

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. There are some paddings around date input element.
2. Radio input button should be larger with color the same as design.

**Comment by amelie314** [comment]
fixed 2 problems

**Review by cwpeng — CHANGES_REQUESTED** [review]
I see no fix on this issue: there are some paddings around date input element.

**Comment by amelie314** [comment]
added the some paddings around date input element!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by amelie314** [comment]
上週作業完成
- 完成API串接
    - 串接註冊功能
    - 串接登入功能
    - 串接查詢登入狀態功能
- 連接資料庫並創建會員table

**Review by cwpeng — CHANGES_REQUESTED** [review]
Where is your website?

**Comment by amelie314** [comment]
Sorry, My website is at:
 http://3.131.18.21:3000/
 
 陳慧樺

**Comment by cwpeng** [comment]
Re-request review from top right corner so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

Don't forget to merge pull request after review approvel. And try to figure out what work flow we applied and why we should do this.

**Pull request merged**
